spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - StripPrefix=2 #porque esta compuesto por 2 segmentos, api y productos
          #- name: Ejemplo
            #args:
              #mensaje: Hola mi mensaje personalizado
              #cookieNombre: usuario
              #cookieValor: AndresGuzman
          #Las 5 lineas anteriores se pueden reemplazar por 
          - EjemploCookie=Hola mi mensaje personalizado, usuario, AndresGuzman
      - id: servicio-item
        uri: lb://servicio-item
        predicates:
          - Path=/api/item/**
        filters:
          - StripPrefix=2 #porque esta compuesto por 2 segmentos, api e item
          - AddRequestHeader=token-request, 1234567 #filtro propio de spring gateway
          - AddResponseHeader=token-response, 12345678 #filtro propio de spring gateway
          - SetResponseHeader=Content-Type, text/plain #esta linea y la linea de EjemploGlobalFilter exchange.getResponse().getHeaders().setContentType(MediaType.TEXT_PLAIN); realizan la misma función
          - AddRequestParameter=nombre, andres
        
        
          
      